Package Installations

In [ ]:
import random
import copy
import time
import pandas as pd
import numpy as np
import gc
import re
import torch as t

#import spacy
from tqdm import tqdm_notebook, tnrange
from tqdm.auto import tqdm

tqdm.pandas(desc='Progress')
from collections import Counter

from nltk.tokenize import word_tokenize
from nltk import pos_tag
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from sklearn.preprocessing import LabelEncoder
from collections import defaultdict
from nltk.corpus import wordnet as wn
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import accuracy_score

import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from torch.nn.utils.rnn import pack_padded_sequence, pad_packed_sequence
from torch.autograd import Variable
import os 

# cross validation and metrics
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import f1_score

from sklearn.preprocessing import StandardScaler
from multiprocessing import  Pool
from functools import partial
from sklearn.decomposition import PCA

import matplotlib.pyplot as plt

In [ ]:
!pip install kaggle

In [ ]:
!pip install transformers

     |████████████████████████████████| 4.0 MB 31.4 MB/s 
     |████████████████████████████████| 895 kB 55.9 MB/s 
     |████████████████████████████████| 596 kB 60.2 MB/s 
     |████████████████████████████████| 6.6 MB 51.3 MB/s 
     |████████████████████████████████| 77 kB 5.4 MB/s 
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13


In [ ]:
!pip install -U torchtext==0.8.0

     |████████████████████████████████| 6.9 MB 30.5 MB/s 
  Attempting uninstall: torchtext
    Found existing installation: torchtext 0.11.0
    Uninstalling torchtext-0.11.0:
      Successfully uninstalled torchtext-0.11.0


In [ ]:
import tensorflow as tf
import torch
import pandas as pd
import numpy as np
import random
from nltk.tokenize import word_tokenize
from nltk import pos_tag
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from collections import defaultdict
from nltk.corpus import wordnet as wn
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, f1_score
from tqdm.notebook import tqdm
from keras.preprocessing.sequence import pad_sequences
from sklearn.preprocessing import LabelEncoder
import transformers
from transformers import GPT2Tokenizer, GPT2ForSequenceClassification, AdamW
from transformers import get_linear_schedule_with_warmup
from torch.utils.data import TensorDataset, DataLoader, RandomSampler, SequentialSampler

In [ ]:
import nltk
nltk.download('punkt')
nltk.download('wordnet')
nltk.download('averaged_perceptron_tagger')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [ ]:
seed_val = 500
random.seed(seed_val)
np.random.seed(seed_val)
torch.manual_seed(seed_val)
torch.cuda.manual_seed_all(seed_val)

Kaggle Dataset

In [ ]:
# Create the kaggle directory and read the uploaded kaggle.json file
!mkdir ~/.kaggle
!cp kaggle.json ~/.kaggle/

mkdir: cannot create directory ‘/root/.kaggle’: File exists


In [ ]:
!chmod 600 /root/.kaggle/kaggle.json

In [ ]:
# Download dataset
!kaggle datasets download -d clmentbisaillon/fake-and-real-news-dataset

fake-and-real-news-dataset.zip: Skipping, found more recently modified local copy (use --force to force download)


In [ ]:
# Unzip folder in Colab content folder
!unzip /content/fake-and-real-news-dataset.zip

Archive:  /content/fake-and-real-news-dataset.zip
replace Fake.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: A
  inflating: Fake.csv                
  inflating: True.csv                


In [ ]:
df1 = pd.read_csv("Fake.csv")
df2 = pd.read_csv("True.csv")
df1["y"] = ["False"]*len(df1)
df2["y"] = ["True"]*len(df2)

In [ ]:
frames = [df1, df2]
corpus = pd.concat(frames, ignore_index=True)

In [ ]:
corpus["x"] = corpus["title"]

In [ ]:
y_encoder = LabelEncoder()
corpus['y'] = y_encoder.fit_transform(corpus['y'])

In [ ]:
corpus = corpus[["x", "y"]]

In [ ]:
corpus.drop_duplicates(inplace=True)
corpus

x  y
0       Donald Trump Sends Out Embarrassing New Year’...  0
1       Drunk Bragging Trump Staffer Started Russian ...  0
2       Sheriff David Clarke Becomes An Internet Joke...  0
3       Trump Is So Obsessed He Even Has Obama’s Name...  0
4       Pope Francis Just Called Out Donald Trump Dur...  0
...                                                  ... ..
44892  North Korea shipments to Syria chemical arms a...  1
44894  LexisNexis withdrew two products from Chinese ...  1
44895  Minsk cultural hub becomes haven from authorities  1
44896  Vatican upbeat on possibility of Pope Francis ...  1
44897  Indonesia to buy $1.14 billion worth of Russia...  1

[38729 rows x 2 columns]

**Reddit Dataset**

In [ ]:
reddit_df = pd.read_csv('/content/news_posts.csv')
reddit_df

Unnamed: 0                                              Title Post Text  \
0              0  People Are Accusing Robinhood Of Stealing From...       NaN   
1              1  US Military Could Lose Space Force Trademark t...       NaN   
2              2  White House threatens to fire anyone who tries...       NaN   
3              3  Meta's threat to close down Facebook and Insta...       NaN   
4              4  Don't eat or inject yourself with disinfectant...       NaN   
...          ...                                                ...       ...   
4898         987  Colorado pizza delivery driver saves mans life...       NaN   
4899         988  Utah Woman Donates Over 1,200 Handmade Toys to...       NaN   
4900         989  Year of the Tiger marks increase in tiger popu...       NaN   
4901         990  Florida cops deliver dresses made by a 99-year...       NaN   
4902         991  85-year-old McDonald's worker recieves $69K in...       NaN   

          ID   Score  Total Comments  \
0     l7afyx  181017            4408   
1     gyzw2p  129257            2844   
2     jrskag  126468            4141   
3     so0ree  126258            3786   
4     g6zci5  125437            7024   
...      ...     ...             ...   
4898  3b37gf   24221             898   
4899  90pbng   24216             888   
4900  sinyqg   24197             205   
4901  8q8njr   24164             183   
4902  9p363i   24160             927   

                                               Post URL  
0     https://www.buzzfeednews.com/article/clarissaj...  
1     https://www.cbr.com/us-military-lose-space-for...  
2     https://americanindependent.com/white-house-th...  
3     https://www.cityam.com/metas-threat-to-close-d...  
4     https://www.cnn.com/world/live-news/coronaviru...  
...                                                 ...  
4898  http://www.postindependent.com/news/16943384-1...  
4899  https://www.insideedition.com/utah-woman-donat...  
4900  https://democratic-europe.eu/2022/02/01/%ef%bf...  
4901  http://www.miamiherald.com/news/state/florida/...  
4902  https://www.wkyt.com/content/news/Friend-helps...  

[4903 rows x 7 columns]

In [ ]:
reddit_df['x'] = reddit_df['Title']

In [ ]:
reddit_df['y'] = ["True"]*4903
reddit_df['y'] = y_encoder.transform(reddit_df['y'])

In [ ]:
reddit_df = reddit_df[["x", "y"]]
reddit_df.drop_duplicates(inplace=True)
reddit_df

/usr/local/lib/python3.7/dist-packages/pandas/util/_decorators.py:311: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return func(*args, **kwargs)


x  y
0     People Are Accusing Robinhood Of Stealing From...  1
1     US Military Could Lose Space Force Trademark t...  1
2     White House threatens to fire anyone who tries...  1
3     Meta's threat to close down Facebook and Insta...  1
4     Don't eat or inject yourself with disinfectant...  1
...                                                 ... ..
4898  Colorado pizza delivery driver saves mans life...  1
4899  Utah Woman Donates Over 1,200 Handmade Toys to...  1
4900  Year of the Tiger marks increase in tiger popu...  1
4901  Florida cops deliver dresses made by a 99-year...  1
4902  85-year-old McDonald's worker recieves $69K in...  1

[4903 rows x 2 columns]

In [ ]:
from sklearn import model_selection
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences

In [ ]:
x_train =corpus['x']
y_train = corpus['y']
x_test = reddit_df['x']
y_test = reddit_df['y']

In [ ]:
embed_size = 300 # how big is each word vector
max_features = 120000 # how many unique words to use (i.e num rows in embedding vector)
maxlen = 750 # max number of words in a question to use
batch_size = 512 # how many samples to process at once
n_epochs = 5 # how many times to iterate over all samples
n_splits = 5 # Number of K-fold Splits
SEED = 10
debug = 0

In [ ]:
## Tokenize the sentences
tokenizer = Tokenizer(num_words=max_features)
tokenizer.fit_on_texts(list(x_train))
x_train = tokenizer.texts_to_sequences(x_train)
x_test = tokenizer.texts_to_sequences(x_test)

## Pad the sentences 
x_train = pad_sequences(x_train, maxlen=maxlen)
x_test= pad_sequences(x_test, maxlen=maxlen)

In [ ]:
print("X_test: ",x_train, x_train.shape, x_train.shape[1])
print("X_test: ",x_test)

X_test:  [[    0     0     0 ...    43    15  1771]
 [    0     0     0 ...    87  1806   379]
 [    0     0     0 ...  7193     8 11526]
 ...
 [    0     0     0 ...  6253    22  2434]
 [    0     0     0 ...  3112  3557    38]
 [    0     0     0 ...     4    87  2404]] (38729, 750) 750
X_test:  [[   0    0    0 ... 3383    7 2227]
 [   0    0    0 ...    1 7428 4371]
 [   0    0    0 ...  514    1 1308]
 ...
 [   0    0    0 ...    3  922  301]
 [   0    0    0 ... 6656    8 2375]
 [   0    0    0 ... 1327    3 2283]]


In [ ]:
!wget http://nlp.stanford.edu/data/glove.6B.zip
!unzip glove.6B.zip
!ls -lat

--2022-04-19 03:21:31--  http://nlp.stanford.edu/data/glove.6B.zip
Resolving nlp.stanford.edu (nlp.stanford.edu)... 171.64.67.140
Connecting to nlp.stanford.edu (nlp.stanford.edu)|171.64.67.140|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://nlp.stanford.edu/data/glove.6B.zip [following]
--2022-04-19 03:21:31--  https://nlp.stanford.edu/data/glove.6B.zip
Connecting to nlp.stanford.edu (nlp.stanford.edu)|171.64.67.140|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://downloads.cs.stanford.edu/nlp/data/glove.6B.zip [following]
--2022-04-19 03:21:32--  http://downloads.cs.stanford.edu/nlp/data/glove.6B.zip
Resolving downloads.cs.stanford.edu (downloads.cs.stanford.edu)... 171.64.64.22
Connecting to downloads.cs.stanford.edu (downloads.cs.stanford.edu)|171.64.64.22|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 862182613 (822M) [application/zip]
Saving to: ‘glove.6B.zip’

glove.6

In [ ]:
## FUNCTIONS TAKEN FROM https://www.kaggle.com/gmhost/gru-capsule

def load_glove(word_index):
    EMBEDDING_FILE = '/content/glove.6B.300d.txt'
    def get_coefs(word,*arr): return word, np.asarray(arr, dtype='float32')[:300]
    embeddings_index = dict(get_coefs(*o.split(" ")) for o in open(EMBEDDING_FILE))
    
    all_embs = np.stack(embeddings_index.values())
    emb_mean,emb_std = -0.005838499,0.48782197
    embed_size = all_embs.shape[1]

    nb_words = min(max_features, len(word_index)+1)
    embedding_matrix = np.random.normal(emb_mean, emb_std, (nb_words, embed_size))
    for word, i in word_index.items():
        if i >= max_features: continue
        embedding_vector = embeddings_index.get(word)
        if embedding_vector is not None: 
            embedding_matrix[i] = embedding_vector
        else:
            embedding_vector = embeddings_index.get(word.capitalize())
            if embedding_vector is not None: 
                embedding_matrix[i] = embedding_vector
    return embedding_matrix

In [ ]:
if debug:
    embedding_matrix = np.random.randn(120000,300)
else:
    embedding_matrix = load_glove(tokenizer.word_index)

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  exec(code_obj, self.user_global_ns, self.user_ns)


In [ ]:
np.shape(embedding_matrix)

(31803, 300)

BiLSTM

In [ ]:
import torch

In [ ]:
class BiLSTM(nn.Module):
    
    def __init__(self):
        super(BiLSTM, self).__init__()
        self.hidden_size = 64
        drp = 0.3
        n_classes = 10
        self.embedding = nn.Embedding(max_features, embed_size)
        self.embedding.weight = nn.Parameter(torch.tensor(embedding_matrix, dtype=torch.float32))
        self.embedding.weight.requires_grad = False
        self.lstm = nn.LSTM(embed_size, self.hidden_size, bidirectional=True, batch_first=True)
        self.linear = nn.Linear(self.hidden_size*4 , 64)
        self.relu = nn.ReLU()
        self.dropout = nn.Dropout(drp)
        self.out = nn.Linear(64, n_classes)


    def forward(self, x):
        #rint(x.size())
        h_embedding = self.embedding(x)
        #_embedding = torch.squeeze(torch.unsqueeze(h_embedding, 0))
        h_lstm, _ = self.lstm(h_embedding)
        avg_pool = torch.mean(h_lstm, 1)
        max_pool, _ = torch.max(h_lstm, 1)
        conc = torch.cat(( avg_pool, max_pool), 1)
        conc = self.relu(self.linear(conc))
        conc = self.dropout(conc)
        out = self.out(conc)
        return out

In [ ]:
n_epochs = 10
model = BiLSTM()
loss_fn = nn.CrossEntropyLoss(reduction='sum')
optimizer = torch.optim.Adam(filter(lambda p: p.requires_grad, model.parameters()), lr=0.001)
model.cuda()

# Load train and test in CUDA Memory
x_train2 = torch.tensor(x_train, dtype=torch.long).cuda()
y_train2 = torch.tensor(y_train.values, dtype=torch.long).cuda()
x_cv = torch.tensor(x_test, dtype=torch.long).cuda()
y_cv = torch.tensor(y_test, dtype=torch.long).cuda()

# Create Torch datasets
train = torch.utils.data.TensorDataset(x_train2, y_train2)
valid = torch.utils.data.TensorDataset(x_cv, y_cv)

# Create Data Loaders
train_loader = torch.utils.data.DataLoader(train, batch_size=batch_size, shuffle=True)
valid_loader = torch.utils.data.DataLoader(valid, batch_size=batch_size, shuffle=False)

train_loss = []
valid_loss = []

for epoch in range(n_epochs):
    start_time = time.time()
    # Set model to train configuration
    model.train()
    avg_loss = 0.  
    for i, (x_batch, y_batch) in enumerate(train_loader):
        # Predict/Forward Pass
        y_pred = model(x_batch)
        # Compute loss
        loss = loss_fn(y_pred, y_batch)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        avg_loss += loss.item() / len(train_loader)
    
    # Set model to validation configuration -Doesn't get trained here
    model.eval()        
    avg_val_loss = 0.
    val_preds = np.zeros((len(x_cv),10))
    
    for i, (x_batch, y_batch) in enumerate(valid_loader):
        y_pred = model(x_batch).detach()
        avg_val_loss += loss_fn(y_pred, y_batch).item() / len(valid_loader)
        # keep/store predictions
        val_preds[i * batch_size:(i+1) * batch_size] =F.softmax(y_pred).cpu().numpy()
    
    # Check Accuracy
    val_accuracy = sum(val_preds.argmax(axis=1)==y_test)/len(y_test)
    train_loss.append(avg_loss)
    valid_loss.append(avg_val_loss)
    elapsed_time = time.time() - start_time 
    print('Epoch {}/{} \t loss={:.4f} \t val_loss={:.4f}  \t val_acc={:.4f}  \t time={:.2f}s'.format(
                epoch + 1, n_epochs, avg_loss, avg_val_loss, val_accuracy, elapsed_time))

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:48: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.


Epoch 1/10 	 loss=328.9032 	 val_loss=888.2661  	 val_acc=0.4006  	 time=17.19s
Epoch 2/10 	 loss=87.3203 	 val_loss=1023.3419  	 val_acc=0.4204  	 time=16.54s
Epoch 3/10 	 loss=68.4002 	 val_loss=1311.2106  	 val_acc=0.3586  	 time=16.04s
Epoch 4/10 	 loss=56.4293 	 val_loss=1163.0708  	 val_acc=0.4532  	 time=16.01s
Epoch 5/10 	 loss=46.1737 	 val_loss=1038.0838  	 val_acc=0.5117  	 time=16.01s
Epoch 6/10 	 loss=38.5157 	 val_loss=1578.8209  	 val_acc=0.3800  	 time=16.02s
Epoch 7/10 	 loss=32.2003 	 val_loss=1542.9458  	 val_acc=0.4375  	 time=16.08s
Epoch 8/10 	 loss=25.3488 	 val_loss=1714.6526  	 val_acc=0.3710  	 time=16.02s
Epoch 9/10 	 loss=20.7818 	 val_loss=2075.2921  	 val_acc=0.3600  	 time=16.00s
Epoch 10/10 	 loss=16.5628 	 val_loss=1799.0986  	 val_acc=0.4412  	 time=16.00s
